[[constraint]]
  branch = "master"
  name = "github.com/BurntSushi/xgb"
  source = "github.com/seeruk/xgb"

[[constraint]]
  branch = "master"
  name = "github.com/golang/protobuf"

[[constraint]]
  branch = "master"
  name = "github.com/gotk3/gotk3"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.7.1"

[[constraint]]
  name = "github.com/inconshreveable/log15"
  version = "2.13.0"
